// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAekU2K2qwbisvtEkakX3d2g6eA478LwHc',
    appId: '1:220852966414:web:4916c4b790d8b390cad85f',
    messagingSenderId: '220852966414',
    projectId: 'flutter-watchlist',
    authDomain: 'flutter-watchlist.firebaseapp.com',
    databaseURL: 'https://flutter-watchlist.firebaseio.com',
    storageBucket: 'flutter-watchlist.appspot.com',
    measurementId: 'G-W2YH6JWLEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk08LrBBTBBTzLzEhivG7XQ_q3mfWzSIk',
    appId: '1:220852966414:android:dbf9be5d2dff263dcad85f',
    messagingSenderId: '220852966414',
    projectId: 'flutter-watchlist',
    databaseURL: 'https://flutter-watchlist.firebaseio.com',
    storageBucket: 'flutter-watchlist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW6HRueRM1cAzEl3lMl4rLgvAm7auc_-I',
    appId: '1:220852966414:ios:58abfb0e4c048917cad85f',
    messagingSenderId: '220852966414',
    projectId: 'flutter-watchlist',
    databaseURL: 'https://flutter-watchlist.firebaseio.com',
    storageBucket: 'flutter-watchlist.appspot.com',
    androidClientId:
        '220852966414-dtn27q5ga3b6vsmg9k4le84drdsmst6i.apps.googleusercontent.com',
    iosClientId:
        '220852966414-1lb77tmb2qfirnffv2mipp124ova3dct.apps.googleusercontent.com',
    iosBundleId: 'com.danr95.flutterWatchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW6HRueRM1cAzEl3lMl4rLgvAm7auc_-I',
    appId: '1:220852966414:ios:58abfb0e4c048917cad85f',
    messagingSenderId: '220852966414',
    projectId: 'flutter-watchlist',
    databaseURL: 'https://flutter-watchlist.firebaseio.com',
    storageBucket: 'flutter-watchlist.appspot.com',
    androidClientId:
        '220852966414-dtn27q5ga3b6vsmg9k4le84drdsmst6i.apps.googleusercontent.com',
    iosClientId:
        '220852966414-1lb77tmb2qfirnffv2mipp124ova3dct.apps.googleusercontent.com',
    iosBundleId: 'com.danr95.flutterWatchlist',
  );
}
